### ISSUE TITLE
R CMD Check and devtools::document() issues

### ISSUE THREAD

**Issue by amoeba** [arcaravaggi/remBoot#17]
I'm not having any luck with having RStudio not clobber my edits into useless diffs so I'll make my comments here. My process for finding these issues is run and re-run `devtools::document` and `devtools::check` until the issues go away.

- Vignette doesn't load `remBoot` at the start and needs to
- Remove @export tags or document these:

```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘grpDat_func’ ‘res_dat’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

- Fix a typo in the docs for `rem`

```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'rem'
  ‘dat’
Documented arguments not in \usage in documentation object 'rem':
  ‘.df’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
- Examples don't run:

```
* checking examples ... ERROR
Running examples in ‘remBoot-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: boot_sd
> ### Title: Required for remsD bootstrapping
> ### Aliases: boot_sd
> 
> ### ** Examples
> 
> ## Define the number of bootstrapping iterations and apply boot_sd to the data:
> nboots <- 1000
> remsD <- lapply(grpDat, boot_sd)
Error in lapply(grpDat, boot_sd) : object 'grpDat' not found
Execution halted
```

There may be more issues after that is fixed.

- Missing import statements:

```
checking R code for possible problems ... NOTE
boot_sd: no visible binding for global variable ‘nboots’
boot_sd: no visible binding for global variable ‘tm’
boot_sd: no visible binding for global variable ‘v’
remBoot: no visible binding for global variable ‘sd’
remBoot: no visible binding for global variable ‘quantile’
Undefined global functions or variables:
  nboots quantile sd tm v
Consider adding
  importFrom("stats", "quantile", "sd")
to your NAMESPACE file.
```

**Comment by arcaravaggi** [comment]
I'll be uploading fixes as a batch, rather than individually.

- Fixed the vignette `remboot` issue.
- Corrected the .df-dat issue in `rem`
- Added documentation in `boot_sd`. However, the note 'no visible binding for global variable [variable name] aren't concerns as they're defined earlier and passed into the function (_tm_, _v_ & _nboots_)
- Removed @export from `grpDat_func` and `res_dat`. Also from `bsD` (it appears to work...)
- NAMESPACE is overwritten every time the package is rebuilt during checking. I've added importFrom("stats", "quantile", "sd") manually.

I'm not getting any remaining issues from the checks.

**Comment by amoeba** [comment]
Great, thanks. Add the @importFrom to the roxygen block for the function to get it to show up in NAMESPACE

**Comment by arcaravaggi** [comment]
Done. Thanks for your patience. 3 notes remain, which aren't of concern:

```checking R code for possible problems ... NOTE   
boot_sd: no visible binding for global variable 'nboots'    
boot_sd: no visible binding for global variable 'tm'   
boot_sd: no visible binding for global variable 'v'   
Undefined global functions or variables:
  nboots tm v```

**Comment by amoeba** [comment]
Excellent, thanks for addressing those. I'll take a look and see if we can finish this out today.

**Comment by arcaravaggi** [comment]
No problem. It's something I should have known to do sooner, really, saving you the trouble. This is all a learning curve for me.

**Comment by amoeba** [comment]
On a fresh pull from master on this repo, I still get an error during `devtools::check`

```
* checking examples ... ERROR
Running examples in ‘remBoot-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: bsD
> ### Title: Required for remsD bootstrapping
> ### Aliases: bsD
> ### Keywords: bootstrap density, encounter model, population, random
>
> ### ** Examples
>
>
> bsD <- function(dat, tm, v){
+ bsDat <- dat[sample(1:nrow(dat), size = nrow(dat), replace = TRUE), ]
+ dOut <- rem(bsDat, tm, v)
+ return(dOut)
+ }
>
>
> remsD <- lapply(grpDat, function(x){
+  d <- replicate(nboots, bsD(dat, tm, v))
+  return(d)
+ })
Error in lapply(grpDat, function(x) { : object 'grpDat' not found
Execution halted
```

**Comment by arcaravaggi** [comment]
My last push didn't remove the bsd.R file (supplanted by the more appropriately named bsD.R) for some reason. I've removed it, done a fresh pull, and got a clean check (apart from those 3 notes).

**Comment by amoeba** [comment]
All good! Thanks.

**Comment by arcaravaggi** [comment]
Great.  Are we good to close this issue?

**Comment by amoeba** [comment]
Yep, good call.

**Comment by yudhihariyawan** [comment]
I always fail when trying to call data. It said data set not found. But, if I call table hDat from exercise, it succeed. Would you please help about this issue? Thanks

**Comment by arcaravaggi** [comment]
Hi yudhihariyawan. I've created a new Issue for this query: https://github.com/arcaravaggi/remBoot/issues/23
